### ISSUE TITLE
problem when compiling master branch of server

### ISSUE THREAD

**Issue by pwin** [oxigraph/oxigraph#53] opened 2020-08-31 14:53 UTC
following the instructions for compiling the server I get the following error

`   Compiling parking v2.0.0
error[E0658]: use of unstable library feature 'checked_duration_since'
   --> C:\Users\Pedro\.cargo\registry\src\github.com-1ecc6299db9ec823\parking-2.0.0\src\lib.rs:144:32
    |
144 |             .park(Some(instant.saturating_duration_since(Instant::now())))
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/58402

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `parking`.
warning: build failed, waiting for other jobs to finish...
error: build failed

`

Any suggestions on resolution?

**Comment by Tpt** [comment] 2020-08-31 15:08
Hi! Thank you for your interest in Oxigraph.

It looks a lot like a compatibility problem with an old version of Rust. It seems that this function has been made available to the stable version of Rust in version 1.39. Which version of Rust are you using (you could use `rustc --version`)?
I currently only test Oxigraph with the recent version of Rust and it is also the case of a lot of Rust library I depend on (the recent Rust versions provide a lot of nice new features). If possible, please use a recent stable version of Rust. If you want, Oxigraph provides already built Docker images.

**Comment by pwin** [comment] 2020-08-31 16:23
Thanks - that's really helpful ... So a `rustup update` and re-run the compilation should sort it

**Comment by Tpt** [comment] 2020-08-31 21:11
Yes!

Please, close this issue if it worked.

**Comment by pwin** [comment] 2020-09-01 08:37
Hi Thomas
I also came across the following requirement for running, there isn't
anything documented in the readme

C:\Users\Pedro\Documents\oxigraph\target\release>oxigraph_server.exe
Required options not provided:
    --file

**Comment by Tpt** [comment] 2020-09-01 10:52
Hi! Nice to see it compiles on Windows. I indeed definitely need to document it. `oxigraph_server.exe --help` should provide the server argument and options. [I have improved the documentation.](https://github.com/oxigraph/oxigraph/commit/1fc952e7fcc303503c8bf6ea396f41bc8c74125f)

**Comment by pwin** [comment] 2020-09-01 11:07
That's brilliant!  thanks
The one thing I'm not seeing work is a sparql describe query - does that
operate OK?  Perhaps I'm entering it incorrectly?

**Comment by Tpt** [comment] 2020-09-01 13:04
I have implemented DESCRIBE but not tested much and there indeed seems to be a problem with it.
I am going to investigate it and add some automated tests to avoid breaking it again in the future.

Before that, you could use `CONSTRUCT WHERE { <my_uri> ?p ?o }` that should do the same thing.

**Comment by Tpt** [comment] 2020-09-01 20:47
I have just [pushed a fix for the DESCRIBE evaluation bug](https://github.com/oxigraph/oxigraph/commit/cd8032136a4503f904f36397a27fe2f2a8d95872). I have also written some tests to prevent regressions.
It will be included in the next 0.2 release (I still have to improve some details around SPARQL UPDATE support before pushing it).

Sorry for this problem and thank you for finding it!

**Comment by Tpt** [comment] 2021-01-07 21:32
Oxigraph 0.2 is now released with a bug fix. Sorry for the delay.

**Closed by Tpt** 2021-01-07 21:32 UTC
