### ISSUE TITLE
XSD datetimes with trailing zeros are loosing precision

### ISSUE THREAD

**Issue by marcelotto** [oxigraph/oxigraph#524] opened 2023-06-04 23:02 UTC
First of all, a big thank you for this wonderful project.

I encountered the following misbehavior: when storing an XSD datetime trailing zeros on the microseconds are cut off, leading to a different value than the original. 

### Current behavior

with oxigraph_server 0.3.16

```sparql
PREFIX ex: <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
  ex:S ex:p "2023-06-04T20:36:33.100000"^^xsd:dateTime .
}
```

```sparql
PREFIX ex: <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT * WHERE {
  ex:S ex:p ?obj .
}
```

Results:

```
{
  "head": {
    "vars": [
      "obj"
    ]
  },
  "results": {
    "bindings": [
      {
        "obj": {
          "type": "literal",
          "value": "2023-06-04T20:36:33.1",
          "datatype": "http://www.w3.org/2001/XMLSchema#dateTime"
        }
      }
    ]
  }
}
```

### Expected behavior

```
{
  "head": {
    "vars": [
      "obj"
    ]
  },
  "results": {
    "bindings": [
      {
        "obj": {
          "type": "literal",
          "value": "2023-06-04T20:36:33.100000",
          "datatype": "http://www.w3.org/2001/XMLSchema#dateTime"
        }
      }
    ]
  }
}
```

**Comment by Tpt** [comment] 2023-06-05 10:02
Hi @marcelotto! Thank you!

That's a great question. Oxigraph stores `xsd:dateTime` as a numerical timestamp using [a fix point decimal type](https://docs.rs/oxsdatatypes/latest/oxsdatatypes/struct.Decimal.html) to make operations like sort much faster and decrease storage space. This decimal type does not keep tracks of precision. Hence, just like for `xsd:decimal` in Oxigraph, "1.0" and "1.000" are identical. This is "normalization" is a small deviation from the SPARQL specification that assumes that literal string values are kept. This deviation is quite common at my knowledge (Jena TDB, Blazegraph...).

I use this encoding because the [XML schema specification](https://www.w3.org/TR/xmlschema11-2/) states that [`xsd:dateTime` second component is a "decimal number"](https://www.w3.org/TR/xmlschema11-2/#vp-dt-second) and that [`xsd:decimal` do not reflect precision in their value space](https://www.w3.org/TR/xmlschema11-2/#decimal). Later in the spec [the `xsd:dateTime` parsing is described as using the same parsing as `xsd:decimal` for each of the date-time component](https://www.w3.org/TR/xmlschema11-2/#rf-lexicalMappings-datetime).

So, I believe the proper way to fix this problem would be to add an option in Oxigraph to disable inlining of date-time value to keep their string representation. What do you think  about it?

**Comment by adamreichold** [comment] 2023-06-05 10:09
> So, I believe the proper way to fix this problem would be to add an option in Oxigraph to disable inlining of date-time value to keep their string representation. What do you think about it?

Maybe optionally storing the precision as numerical datum might be more efficient? Or there is any other information in the string literal which would not be reproduced in this manner?

**Comment by Tpt** [comment] 2023-06-05 10:23
> Maybe optionally storing the precision as numerical datum might be more efficient? Or there is any other information in the string literal which would not be reproduced in this manner?

There are some extra details with timezone like UTC that can be written `Z` or `+00:00` or `-00:00`.

**Comment by marcelotto** [comment] 2023-06-05 10:53
I understand. That's a tough trade-off decision.

Some more details on my specific use case, that might be of interest: I stumbled across this problem with some flaky tests in my test suite using the current time which failed occasionally when these ended with trailing zeros. One interesting fact is, that I actually don't work directly on the lexical representation, but with the datetime value representation in Elixir, which stores the microseconds part as a tuple of two integers, one for the actual value and one for the precision.

> This deviation is quite common at my knowledge (Jena TDB, Blazegraph...).

Having Ontotext GraphDB at hand, I quickly tested its behavior and got the original datetime with the correct precision back.

> So, I believe the proper way to fix this problem would be to add an option in Oxigraph to disable inlining of date-time value to keep their string representation. What do you think about it?

Sounds indeed like the best option, when there's no efficient alternative that keeps the original representation.

**Comment by Tpt** [comment] 2023-06-11 16:58
I allow myself to close this issue. There is an other one with the solution idead;

**Closed by Tpt** 2023-06-11 16:58 UTC
Labels: bug
